### ISSUE TITLE
NOT AN ISSUE, just don't know how to contact the owner of this repo

### ISSUE THREAD

**Issue by lew-kas** [tgmerritt/sophie_in_node#2]
First of all, sorry I created an issue for this.. just don't know how to contact you.

I am currently trying to figure out how to use emotions for my "digital human". 
Therefore I created a custom payload in my Dialogflow Intent : 

**{"instructions":{"emotionalTone":[{"tone":"happiness","start":0.1,"value":1,"default":true,"duration":8}]}}**

In the response I can see that the value is set correctly, but my Digital Human doesn't use the given emotions. 
I dont have a project, I simply use the Uneeq Admin-UI combined with my Dialogflow API.

Sincerely
lew-kas

**Comment by tgmerritt** [comment]
Hi Lew-kas - you can email me at tylerm@uneeq.com and we can help you any time.

I think that you're using one of our newer digital humans, and the animation system has changed.  What you're doing is correct - but for the older system.  I'll make a note of this and update the project README - the new documentation is almost finished.  In short, what you're doing isn't wrong, but is now incompatible with the new digital humans, and a new animation system will be published hopefully this week.
